version: '3.9'
services:
  pgdb_server:
    image: postgres:13.2
    restart: always
    environment:
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testpass
      - POSTGRES_DB= returndb
    ports:
      - "5432:5432"
    volumes:
      - /home/r_nasiri/pgdata:/var/lib/postgresql/data
volumes:
  db:
    driver: local